### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by ryobg** [dokterbob/ipfs-search#2]
Hello! 

Its really nice to have such search engine. Mainly because if you want to check whether something to exist you have no other way. There is no such thing as catalogue or so. Hence a search engine as this one seems really useful. I have troubles though using it. Maybe other people can have the same issues too.

Basically, I do not know what it does and how it works. Can there be some examples or short doc or help or so? For example I have just typed there "doxygen" and got some results, but I have no idea what the title with the icon means - it says "d", "D", "t", <some hash>? Also can I search by filename? Basically that's what I want in this case - not the content so much as the file name (really nice to have some regular expressions btw).

Small hint, I see IPFS guys do that too, but IMHO the size in bytes should be in human readable form i.e. Kb, Mb, Gb and etc.

Best Regards!

**Comment by dokterbob** [comment]
Hey,

Thanks for the feedback.

As you might know, IPFS objects (or files) have no native names unless they’re in directories. Hence, objects with ‘weird’ names are somehow referenced from directories with these names.

Directory entries are indeed searched, however, I have not implemented a way to filter by object type - you’re welcome to create a GitHub issue for that.

The same goes for human readable file sizes; it has simply not yet been implemented.

**Comment by ryobg** [comment]
Thank you for your answer! I have missed somewhat the fact that the names are erased. Which brings me to wonder what should be the way to map hashes to hm... something which you can understand. 

I have really bundled few things at the same time: help, file sizes and object filters. I think this issue can be just reused. Or closed if you see this as more proper action.

**Comment by dokterbob** [comment]
Names aren't erased if you always add them from within a containing folder. However, there can be multiple references to the same object.

Anyways; I can use help like you, this is an open source endeavor. You would safe me time by creating seperate issues for the file size and object type filters, describing them. Maybe even someone else contributes solutions to them!
